services:
  datafoundry:
    image: datafoundrydocker:production
    container_name: datafoundrydocker
    ports:
      - "9000:9000"
      - "8001:8001"
      - "9092:9092"
    volumes:
    # Change this to change the data directory on the host system (E.g: /home/diede/database:/home/datafoundry/data)
      - .data/development:/app/data

  # TODO: Setup for postgres