-- change project table

# --- !Ups
ALTER TABLE project ADD COLUMN frozen_project boolean default false not null;

create table reference (
  id                            bigint generated by default as identity not null,
  owning_project_id             bigint,
  referenced_project_id         bigint,
  reference_information         TEXT,
  created                       timestamp,
  constraint pk_reference primary key (id)
);

create index ix_reference_owning_project_id on reference (owning_project_id);
alter table reference add constraint fk_reference_owning_project_id foreign key (owning_project_id) references project (id) on delete restrict on update restrict;

create index ix_reference_referenced_project_id on reference (referenced_project_id);
alter table reference add constraint fk_reference_referenced_project_id foreign key (referenced_project_id) references project (id) on delete restrict on update restrict;


# --- !Downs
ALTER TABLE project DROP COLUMN frozen_project;

drop table if exists reference;

alter table reference drop constraint if exists fk_reference_owning_project_id;
drop index if exists ix_reference_owning_project_id;

alter table reference drop constraint if exists fk_reference_referenced_project_id;
drop index if exists ix_reference_referenced_project_id;
