# -------------------------------------------------------------------
# Reference configuration
#
#
# -------------------------------------------------------------------
# Documentation
# https://www.playframework.com/documentation/latest/ConfigFile
# -------------------------------------------------------------------

play.modules {
  enabled += "play.filters.hosts.AllowedHostsModule"
  enabled += "play.filters.gzip.GzipFilterModule"
}

play.filters.headers.frameOptions = "SAMEORIGIN"
play.filters.enabled += play.filters.cors.CORSFilter
play.filters.disabled += play.filters.csrf.CSRFFilter

play.filters.csp.CSPFilter = "default-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' 'unsafe-inline' data: *; connect-src 'self' https://api.fitbit.com/; frame-ancestors 'self';"

play.filters.hosts {
  allowed = ["."]
}

play.filters.cors {
  pathPrefixes = ["/"]
  allowedOrigins = ["*"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE"]
  supportsCredentials = false
  preflightMaxAge = 3 days
}

pekko.http {
  parsing {
    max-uri-length = 16k
  }
}

# Ebean configuration
# ~~~~~
# You can declare as many Ebean servers as you want.
# By convention, the default server is named `default`
ebean.default=["models.*"]

# Number of database connections
# See https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
fixedConnectionPool = 9

# Set Hikari to fixed size
play.db {
  prototype {
    hikaricp.minimumIdle = ${fixedConnectionPool}
    hikaricp.maximumPoolSize = ${fixedConnectionPool}
  }
}
jpa.default=defaultPersistenceUnit

# Job queue sized to HikariCP connection pool
database.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = ${fixedConnectionPool}
  }
}

play.evolutions.enabled = true


# Misc configuration
# ~~~~~

play.http.errorHandler = "utils.ErrorHandler"

play.temporaryFile {
  reaper {
    enabled = true
    initialDelay = "5 minutes"
    interval = "30 seconds"
    olderThan = "30 minutes"
  }
}

# languages
play.i18n.langs = [ "en", "nl", "de" ]

# upload file size limitation
play.http.parser.maxDiskBuffer = 30MB
play.http.parser.maxMemoryBuffer = 1024K
parsers.anyContent.maxLength = 30MB
